name: 'Pod Status'
description: Checks to see if a given pod is running in GKE.
author: Colin Campbell
inputs:
  gkeApplicationCredentials:
    description: The service account credentials JSON file encoded as a base64 string to access the GKE API.
    required: true
  gkeNamespace:
    description: The Kubernetes cluster's namespace.
    required: true
  gkeProjectID:
    description: The GKE project identifier (kube-cluster-12345).
    required: true
  gkeClusterName:
    description: The name of the Kubernetes cluster.
    required: true
  gkeLocationZone:
    description: The cluster's location zone.
    required: true
  podNames:
    description: A list of pod names to check.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
